### ISSUE TITLE
Program exits mid-generating

### ISSUE THREAD

**Issue by sykman123** [icosmo11/seed-phrase-generator#1]
Hey!

I got an issue while running your program, every time i start the generating process the program exits after a certain amount of time(always at 3-4000 generated seeds) and closes with no error message or warning or whatsoever...

Can you please try help me find the source of the problem?

https://github.com/user-attachments/assets/971494bb-7d47-4090-a7a7-b6cbdbc17185

**Comment by icosmo11** [comment]
Hello! Try running the program via cmd, the reason for the program failure should be displayed there
